# Generated by Django 6.0.2 on 2026-02-23 08:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_task_done'),
    ]

    operations = [
        migrations.RenameField(
            model_name='task',
            old_name='descripton',
            new_name='description',
        ),
    ]
